<div class="box">
  <!--エラーメッセージ-->
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <%= @contact.errors.count %>件のエラーが発生しました
      <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="box-inner">
    <%= form_with model: @contact, url: contacts_path, method: :post, local:true do |f| %>
      <h1 class="exhibition">お問い合わせ</h1>
      <div class="box-name">
        <%= f.label :名前 ,class: "style" %><br>
        <%= f.text_field :name, size: "40x5",  autofocus: true %>
      </div>
      <div class="box-mail">
        <%= f.label :メールアドレス ,class: "style" %><br>
        <%= f.text_field :email, size: "40x5", autofocus: true %>
      </div>
      <div class="box-phone">
        <%= f.label :電話番号 ,class: "style" %><br>
        <%= f.text_field :phone_number, size: "40x5",  autofocus: true %>
      </div>
      <div class="box-content">
        <%= f.label :お問い合わせ内容 ,class: "style" %><br>
        <%= f.text_area :content, size: "40x5",  autofocus: true %>
      </div>
      <div class="box-login">
        <%= f.submit "送信" %>
      </div>
    <% end %>
  </div>
</div>